"""initial_migration

Revision ID: 2bcde4b14fa8
Revises: 
Create Date: 2026-09-19 01:28:05.921893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bcde4b14fa8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=16), nullable=False),
    sa.Column('is_multiplayer', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('victory_type', sa.String(length=64), nullable=True),
    sa.Column('loss_reason', sa.String(length=64), nullable=True),
    sa.Column('days_survived', sa.Integer(), nullable=True),
    sa.Column('fire_level', sa.Integer(), nullable=True),
    sa.Column('sos_progress', sa.Integer(), nullable=True),
    sa.Column('radio_repaired', sa.Boolean(), nullable=True),
    sa.Column('tower_breached', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_id'), 'game_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_game_sessions_room_id'), 'game_sessions', ['room_id'], unique=True)
    op.create_table('player_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=64), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('is_alive', sa.Boolean(), nullable=True),
    sa.Column('health', sa.Integer(), nullable=True),
    sa.Column('warmth', sa.Integer(), nullable=True),
    sa.Column('hunger', sa.Integer(), nullable=True),
    sa.Column('inventory_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_records_id'), 'player_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_records_id'), table_name='player_records')
    op.drop_table('player_records')
    op.drop_index(op.f('ix_game_sessions_room_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_id'), table_name='game_sessions')
    op.drop_table('game_sessions')
    # ### end Alembic commands ###
